# Generated by Django 5.2.5 on 2025-08-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh_harvest', '0002_remove_user_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
